package ru.arcadudu.danatest_v030.utils

const val CONST_PAIRSET_TO_TEST_TAG = "pairsetToTestTag"


// SHARED PREFERENCES
const val APP_SHARED_PREFERENCES_NAME = "SHARED_PREFERENCES"
const val SHARED_PREFERENCES_PAIRSET_LIST = "SHARED_PREFERENCES_PAIRSET_LIST"




