package ru.arcadudu.danatest_v030.utils

const val CONST_PAIRSET_TO_TEST_TAG = "pairsetToTestTag"


// SHARED PREFERENCES
const val APP_SHARED_PREFERENCES_NAME = "SHARED_PREFERENCES"
const val SHARED_PREFERENCES_PAIRSET_LIST = "SHARED_PREFERENCES_PAIRSET_LIST"

// FROM PAIRSET FRAGMENT TO EDITOR
const val SELECTED_PAIRSET_TO_EDITOR_TAG = "SELECTED_PAIRSET_TO_EDITOR"
const val SELECTED_PAIRSET_ID_TO_EDITOR_TAG = "SELECTED_PAIRSET_ID_TO_EDITOR"

// PAIRSET ID PROVIDER
const val SHARED_PREFERENCES_PAIRSET_ID_LIST = "SHARED_PREFERENCES_PAIRSET_ID_LIST"

// RESULT DIALOG RESTORED ON RESUME
const val IS_RESULT_DIALOG_RESTORED_ON_RESUME = "IS_RESULT_DIALOG_RESTORED_ON_RESUME"
const val IS_RESULT_DIALOG_SHOWN = "IS_RESULT_DIALOG_SHOWN"

// PAIRSET COLOR
const val PAIRSET_COLOR_DEFAULT = "PAIRSET_COLOR_DEFAULT"
const val PAIRSET_COLOR_BLUE = "PAIRSET_COLOR_BLUE"
const val PAIRSET_COLOR_GREEN = "PAIRSET_COLOR_GREEN"
const val PAIRSET_COLOR_RED = "PAIRSET_COLOR_RED"
const val PAIRSET_COLOR_GREY = "PAIRSET_COLOR_GREY"
const val PAIRSET_COLOR_VIOLET = "PAIRSET_COLOR_VIOLET"






